### ISSUE TITLE
Why aren't muparser exceptions inherited from std::exception?

### ISSUE THREAD

**Issue by samerafach** [beltoforion/muparser#27]
Inheriting from std::exception is very helpful, as it helps in getting the operating system to read the error message if the exception is not caught. I see that you have a message part of the exception, and an error code, etc. How about you inherit from std::exception, and then override that `what()` to return something like: "Error [code]: [error message]"?

Is there a particular reason why muparser exceptions are not inherited from std::exception in muparser?

**Comment by beltoforion** [comment]
std::exception::what is returning a const char* for the error messages. That is unusable for an application which aims for support of wide strings.

**Comment by samerafach** [comment]
Whether this is unstable, is debatable, but anyway, you can provide the option for both! You can keep the current options as is, and still inherit from std::exception and override `std::exception::what()`. Would you consider that?

**Comment by beltoforion** [comment]
I said unusable not unstable. Sorry but I have no intention of supporting what() and std::exception because i consider it an undesireable workaround. By supporting what() the parser implies the ability to provide a proper error message. For unicode builds i cannot do that.  In the end your proposal would create a class which violates the Liskov substitution principle. One might argue that this wouldn't be much of a deal but people will end up bothering me with questions why its not working as they expect and no one will read the documentation.
