### ISSUE TITLE
Restricted access to documentation on website

### ISSUE THREAD

**Issue by ebertmp** [beltoforion/muparser#79]
It appears that the bulk of the API documentation is not kept in the repository, but instead is located at the following "private web page." 

http://muparser.beltoforion.de

I have found that access to this website is often blocked by corporate IT security policies making it very difficult to access important sections of the documentation.

**Comment by beltoforion** [comment]
Are you sure the page is beeing blocked? I updated the documentation, the new URL is:

https://beltoforion.de/en/muparser

There is no proper forwarding for the olf page right now. 

I used to have the documentation inside the project but noways everyone is always online and maintaining the documentation in the repository was too much work. Apart from this the new documentation is using PHP and requires a webserver.  There is still the doxyfile though that can be used to create an API documentation.

**Comment by ebertmp** [comment]
I guess strictly speaking the site might not be blocked, but, unfortunately for me, I cannot access the URL from within my employer's network due, I'm pretty sure, to our institutional IT security policies. I get messages like "The server at beltoforion.de is taking too long to respond", but only while I'm using a VPN to connect into my employers network or when I'm actually in the office. One of the folks I collaborate with at another institution has reported similar behavior.  We may be outliers though.

I'd volunteer to help move the documentation into the repository, but it sounds like that is not the direction you want to go. I completely understand not wanting to maintain multiple sets of documentation.

Thank you for this library!

**Comment by beltoforion** [comment]
I would only add the documentation when there is an easy way to maintain it. I removed it because is was perpetually outdated and I cannot bring myself to maintain two versions of the documentation again.

However to solve yout very specific problem. You can always use wget to get an offline copy of a web page. For the muparser web page the command is:

<pre>wget --recursive --no-clobber --page-requisites --html-extension --convert-links --domains beltoforion.de --no-parent https://beltoforion.de/en/muparser/ </pre>

I tried doing this and it appears to work. You can find an offline version of the muparser section from my web page here:

https://drive.google.com/file/d/1tI_PtnnWxn2kxL5qNRv-K5QflPvGP7b6/view?usp=sharing

I'm not sure whether i will add this to the repository in one form or another.

**Comment by ebertmp** [comment]
I tried wget, but this was also blocked by the proxy server. Thanks for the suggestion though. I was able to put together a pdf copy of the website documentation from my personal computer, so I can move forward with that. Thanks again.
